<?php

########################################################################
# Extension Manager/Repository config file for ext: "onpage_seo"
#
# Auto generated by Extension Builder 2013-04-27
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'OnPage SEO',
	'description' => 'SEO for TYPO3',
	'category' => 'plugin',
	'author' => 'Arne Lorenz',
	'author_email' => 'me@arnelorenz.de',
	'author_company' => 'LRNZ',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>